sudo: required

services:
  - docker

branches:
  except:
    - dev
  only:
    - master

before_install:
  - sudo service postgresql stop
  - sudo apt-get update
  - docker-compose build
  - docker ps

script:
  - docker-compose up