sudo: required

services:
  - docker

branches:
  except:
    - dev
  only:
    - master

before_install:
  - sudo service postgresql stop
  - sudo apt-get update

  - docker ps
script:
  - docker-compose build

after_script:
  - docker-compose up
  - curl localhost:8000
  - docker-compose down