sudo: required

services:
  - docker

branches:
  only:
    - master
    - dev

before_install:
  - sudo service postgresql stop
  - sudo apt-get update

script:
- docker-compose build
- docker ps

after_script:
  - docker-compose up &
  - jobs
  - bg 1
  - sleep 120 
  - curl localhost:8000
  - docker-compose down