sudo: required

services:
  - docker

branches:
  except:
    - dev
  only:
    - master

before_install:
  - sudo service postgresql stop
  - sudo apt-get update

script:
- docker-compose build
- docker ps

after_script:
  - travis_wait 5 docker-compose up
  - curl localhost:8000
  - docker-compose down