version: '3'
services:
  web:
    build: ./web
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    ports:
      - '8000:8000'
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
 #   restart: always
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
